server:
  port: 8081
spring:
  application:
    name: metaj
  mvc:
    servlet:
      load-on-startup: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/metaj?serverTimezone=UTC
    username: root
    password: whtly3018107154
  redis:
    #    host: 127.0.0.1
    #    port: 6379
    cluster:
      nodes: 127.0.0.1:6379,127.0.0.1:6380,127.0.0.1:6381,127.0.0.1:6382,127.0.0.1:6383,127.0.0.1:6384
      max-redirects: 3
    timeout: 5000
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com.tiiaan.metaj: debug